import { describe, it, beforeEach, afterEach } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import os from "node:os";
import { initProject } from "./commands/init.js";
import { createWard } from "./commands/ward-create.js";
import { updateWardStatus } from "./commands/ward-status.js";
import { completeWard } from "./commands/ward-complete.js";
import { parseFrontmatter, serializeFrontmatter } from "./frontmatter.js";
import { extractSection } from "./utils/section.js";
import { getClaudeSkills } from "./templates/adapter-content.js";

let tmpDir: string;

function setup(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), "wdd-test-"));
}

function cleanup(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

async function createWardInGold(dir: string, name: string): Promise<number> {
  await createWard(dir, { name, epic: "core", layer: "typescript", tests: 3 });
  const num = fs
    .readdirSync(path.join(dir, ".wdd", "wards"))
    .filter((f) => /^ward-\d+\.md$/.test(f))
    .length;
  await updateWardStatus(dir, num, "red");
  await updateWardStatus(dir, num, "approved");
  await updateWardStatus(dir, num, "gold");
  return num;
}

describe("Ward 015: Manual Smoke Test in Templates", () => {
  beforeEach(async () => {
    tmpDir = setup();
    await initProject(tmpDir, { name: "smoke-test-project" });
  });

  afterEach(() => {
    cleanup(tmpDir);
  });

  // Test 1: New ward files contain Manual Smoke Test section
  it("create_ward_has_smoke_test_section", async () => {
    await createWard(tmpDir, {
      name: "Some Feature",
      epic: "core",
      layer: "typescript",
      tests: 5,
    });

    const wardPath = path.join(tmpDir, ".wdd", "wards", "ward-001.md");
    const content = fs.readFileSync(wardPath, "utf-8");
    const { body } = parseFrontmatter(content);

    assert.ok(
      body.includes("## Manual Smoke Test"),
      "Body should include Manual Smoke Test heading"
    );
    assert.ok(
      body.includes("### Setup"),
      "Smoke test section should include Setup subsection"
    );
    assert.ok(
      body.includes("### Steps"),
      "Smoke test section should include Steps subsection"
    );
    assert.ok(
      body.includes("### Pass criteria"),
      "Smoke test section should include Pass criteria subsection"
    );
  });

  // Test 2: .wdd/templates/ward.md generated by init contains the section
  it("init_template_has_smoke_test", () => {
    const templatePath = path.join(
      tmpDir,
      ".wdd",
      "templates",
      "ward.md"
    );
    const content = fs.readFileSync(templatePath, "utf-8");

    assert.ok(
      content.includes("## Manual Smoke Test"),
      "Template file should include Manual Smoke Test heading"
    );
    assert.ok(
      content.includes("### Setup"),
      "Template should include Setup subsection"
    );
    assert.ok(
      content.includes("### Pass criteria"),
      "Template should include Pass criteria subsection"
    );
  });
});

describe("Ward 015: extractSection Utility", () => {
  // Test 3: Extract content between `## Heading` and next `## `
  it("extract_section_basic", () => {
    const body = `# Ward 015: Example

## Scope
This is the scope.

## Manual Smoke Test
### Setup
Build it.

### Steps
1. Do thing
2. Verify thing

### Pass criteria
- [ ] Works

## Verification
Final notes.
`;

    const result = extractSection(body, "Manual Smoke Test");

    assert.ok(
      result.includes("### Setup"),
      `Should contain Setup subsection. Got: ${result}`
    );
    assert.ok(
      result.includes("### Steps"),
      "Should contain Steps subsection"
    );
    assert.ok(
      result.includes("### Pass criteria"),
      "Should contain Pass criteria subsection"
    );
    assert.ok(
      !result.includes("## Verification"),
      "Should NOT bleed into next ## section"
    );
    assert.ok(
      !result.includes("## Scope"),
      "Should NOT include preceding ## sections"
    );
  });

  // Test 4: Returns empty string when heading not found
  it("extract_section_missing", () => {
    const body = `# Ward 001: Old Ward

## Scope
This is the scope.

## Verification
Done.
`;

    const result = extractSection(body, "Manual Smoke Test");
    assert.equal(result, "", "Should return empty string when heading absent");
  });

  // Test 5: Handles heading at end of body (no following ## heading)
  it("extract_section_at_end", () => {
    const body = `# Ward 015: Example

## Scope
The scope.

## Manual Smoke Test
### Setup
Last section.

### Steps
1. Final step
`;

    const result = extractSection(body, "Manual Smoke Test");

    assert.ok(
      result.includes("### Setup"),
      "Should extract content even when section is last"
    );
    assert.ok(
      result.includes("Final step"),
      "Should include all content to EOF"
    );
  });
});

describe("Ward 015: complete prints smoke test", () => {
  beforeEach(async () => {
    tmpDir = setup();
    await initProject(tmpDir, { name: "smoke-test-project" });
  });

  afterEach(() => {
    cleanup(tmpDir);
  });

  // Test 6: completeWard output includes smoke test when section is present
  it("complete_prints_smoke_test", async () => {
    const num = await createWardInGold(tmpDir, "Smoke Demo Ward");

    // Replace the placeholder smoke test with identifiable content
    const wardPath = path.join(
      tmpDir,
      ".wdd",
      "wards",
      `ward-${String(num).padStart(3, "0")}.md`
    );
    const content = fs.readFileSync(wardPath, "utf-8");
    const { frontmatter, body } = parseFrontmatter(content);

    const customBody = body.replace(
      /## Manual Smoke Test[\s\S]*?(?=\n## |$)/,
      `## Manual Smoke Test
### Setup
SMOKE_SETUP_MARKER

### Steps
1. SMOKE_STEP_MARKER

### Pass criteria
- [ ] SMOKE_PASS_MARKER
`
    );
    fs.writeFileSync(
      wardPath,
      serializeFrontmatter(frontmatter as Record<string, unknown>, customBody)
    );

    const result = await completeWard(tmpDir, num);

    const smokeStep = result.steps.find((s) =>
      s.includes("Manual Smoke Test")
    );
    assert.ok(
      smokeStep,
      `Should include a step mentioning Manual Smoke Test. Steps: ${JSON.stringify(result.steps)}`
    );
    assert.ok(
      smokeStep!.includes("SMOKE_SETUP_MARKER") ||
        smokeStep!.includes("SMOKE_STEP_MARKER") ||
        smokeStep!.includes("SMOKE_PASS_MARKER"),
      `Smoke step should contain extracted content from ward body. Got: ${smokeStep}`
    );
  });

  // Test 8: /ward skill instructs AI to perform smoke test before Gold approval
  it("ward_skill_has_smoke_directive", () => {
    const skills = getClaudeSkills("test-project");
    const ward = skills.find((s) => s.dir === "ward");
    assert.ok(ward, "/ward skill should exist");

    const lower = ward!.content.toLowerCase();
    assert.ok(
      lower.includes("smoke test"),
      "/ward skill must mention smoke test"
    );
    // Must tie smoke test to the Gold-phase approval gate, not just mention it
    assert.ok(
      lower.includes("gold") || lower.includes("before approval"),
      "/ward skill must connect smoke test to Gold approval gate"
    );
  });

  // Test 9: /ward-new skill instructs AI to fill in Manual Smoke Test section when writing spec
  it("ward_new_skill_has_smoke_section_reminder", () => {
    const skills = getClaudeSkills("test-project");
    const wardNew = skills.find((s) => s.dir === "ward-new");
    assert.ok(wardNew, "/ward-new skill should exist");

    const lower = wardNew!.content.toLowerCase();
    assert.ok(
      lower.includes("manual smoke test") || lower.includes("smoke test"),
      "/ward-new skill must mention Manual Smoke Test"
    );
    // Must instruct that the smoke test section is part of the spec being written
    assert.ok(
      lower.includes("spec") || lower.includes("section") || lower.includes("fill"),
      "/ward-new must instruct that smoke test is a section in the spec to fill in"
    );
  });

  // Test 7: legacy ward without smoke test section still completes
  it("complete_handles_no_smoke_test", async () => {
    const num = await createWardInGold(tmpDir, "Legacy Ward");

    // Strip the Manual Smoke Test section to simulate a legacy ward
    const wardPath = path.join(
      tmpDir,
      ".wdd",
      "wards",
      `ward-${String(num).padStart(3, "0")}.md`
    );
    const content = fs.readFileSync(wardPath, "utf-8");
    const { frontmatter, body } = parseFrontmatter(content);

    const legacyBody = body.replace(
      /## Manual Smoke Test[\s\S]*?(?=\n## |$)/,
      ""
    );
    fs.writeFileSync(
      wardPath,
      serializeFrontmatter(frontmatter as Record<string, unknown>, legacyBody)
    );

    // Should not throw — legacy compatibility
    const result = await completeWard(tmpDir, num);

    // Existing reminders (commit, CONTEXT.md) should still be present
    assert.ok(
      result.steps.some((s) => s.includes("commit")),
      "Should still include commit reminder"
    );
    assert.ok(
      result.steps.some((s) => s.includes("CONTEXT.md")),
      "Should still include CONTEXT.md reminder"
    );

    // No smoke-test step should be present
    const smokeStep = result.steps.find((s) =>
      s.includes("Manual Smoke Test")
    );
    assert.ok(
      !smokeStep,
      `Should NOT include smoke test step on legacy ward. Got: ${smokeStep}`
    );
  });
});
